# .upptimerc.yml
owner: it4pyme
repo: it4pyme-status

sites:
  # --- GRUPO 1: PROPIOS ---
  - name: Web IT4PYME
    url: https://it4pyme.es
    method: GET
    icon: https://it4pyme.es/favicon.png
    
  - name: Herramientas PDF
    url: https://pdf.it4pyme.es
    method: GET

  # --- GRUPO 2: MSP INTERNO ---
  - name: RMM Service (Panel Europa)
    url: https://it4pyme.rmmservice.eu
    method: GET

  - name: Bitdefender GravityZone
    url: https://gravityzone.bitdefender.com
    method: GET

  # --- GRUPO 3: CLIENTES Y TERCEROS ---
  - name: Microsoft 365 Login
    url: https://login.microsoftonline.com
    method: GET
  
  # CAMBIO CLAVE: Usamos la web informativa de Gmail, que siempre da 200 OK
  # La url directa a mail.google.com da redirecciones que a veces fallan
  - name: Google Workspace (Gmail)
    url: https://www.google.com/gmail/about/
    method: GET

  # --- GRUPO 4: INFRAESTRUCTURA (DNS) ---
  - name: Google DNS
    check: "tcp-ping"
    url: 8.8.8.8
    port: 53

  - name: Cloudflare DNS
    url: 1.1.1.1
    check: "tcp-ping"

status-website:
  cname: status.it4pyme.es
  baseUrl: /
  logoUrl: https://it4pyme.es/logos/it4pyme-logotipo-claro.svg
  name: IT4PYME Status
  introTitle: "Estado de Sistemas"
  introMessage: "Panel de monitorización en tiempo real."
  
  navbar:
    - title: Volver a Web
      href: https://it4pyme.es
    - title: Soporte
      href: https://it4pyme.es/contacto

  # CONFIGURACIÓN DE ESTÉTICA
  theme: dark
  css: |
    :root {
      --bg-color: #0f172a;
      --card-bg-color: #1e293b;
      --text-color: #f8fafc;
      --link-color: #f97316;
      --success-color: #22c55e;
      --error-color: #ef4444;
      --warning-color: #eab308;
      --u-primary: #f97316;
    }
    body { font-family: 'Inter', sans-serif; }
    .hero { background: linear-gradient(to bottom right, #0f172a, #1e293b); border-bottom: 1px solid #334155; }
    .box { border: 1px solid #334155; border-radius: 0.75rem; }
    #logo { max-height: 3.5rem; }
    footer { font-size: 0.875rem; opacity: 0.6; }

i18n:
  activeIncidents: "Incidencias Activas"
  allSystemsOperational: "✅ Todo operativo"
  incidentReport: "Informe de incidente"
  serviceUnderMaintenance: "🛠 Mantenimiento"
  majorOutage: "🔴 Caída Total"
  partialOutage: "🟠 Caída Parcial"
  degradedPerformance: "🟡 Rendimiento Degradado"
  uptime: "Disponibilidad"
