# .upptimerc.yml
owner: it4pyme
repo: it4pyme-status

sites:
  # --- GRUPO 1: SERVICIOS CRÍTICOS (PROPIOS) ---
  - name: Web IT4PYME
    url: https://it4pyme.es
    method: GET
    icon: https://it4pyme.es/favicon.png
    
  - name: Herramientas PDF
    url: https://pdf.it4pyme.es
    method: GET

  # --- GRUPO 2: HERRAMIENTAS MSP (INTERNAS) ---
  - name: RMM Service (Panel Europa)
    url: https://it4pyme.rmmservice.eu
    method: GET

  - name: Bitdefender GravityZone
    url: https://gravityzone.bitdefender.com
    method: GET

  # --- GRUPO 3: SERVICIOS DE CLIENTES (Globales) ---
- name: Microsoft 365 Login
    url: https://login.microsoftonline.com
    method: GET

- name: Gmail Service (IMAP)
    url: imap.gmail.com
    check: "tcp-ping"
    port: 993

  # --- GRUPO 4: INFRAESTRUCTURA MUNDIAL (DNS) ---
  - name: Cloudflare DNS
    url: 1.1.1.1
    check: "tcp-ping"
    
  - name: Google DNS
    url: 8.8.8.8
    check: "tcp-ping"
    port: 53

status-website:
  cname: status.it4pyme.es
  baseUrl: /
  logoUrl: https://it4pyme.es/logos/it4pyme-logotipo-claro.svg
  name: Estado de Sistemas
  introTitle: "Panel de Estado Operativo"
  introMessage: "Monitorización en tiempo real de nuestros servicios, herramientas de gestión e infraestructura crítica global."
  
  navbar:
    - title: Volver a IT4PYME
      href: https://it4pyme.es
    - title: Abrir Ticket
      href: https://it4pyme.es/contacto

  # CONFIGURACIÓN DEL ESTILO
  theme: dark
  css: |
    :root {
      --bg-color: #0f172a; /* Slate-900 */
      --card-bg-color: #1e293b; /* Slate-800 */
      --text-color: #f8fafc; /* Slate-50 */
      --link-color: #f97316; /* Orange-500 */
      --success-color: #22c55e; /* Green-500 */
      --error-color: #ef4444; /* Red-500 */
      --warning-color: #eab308; /* Yellow-500 */
      --u-primary: #f97316;
    }
    body { font-family: 'Inter', system-ui, sans-serif; }
    /* Hero Gradient */
    .hero { background: linear-gradient(to bottom right, #0f172a, #1e293b); border-bottom: 1px solid #334155; }
    /* Cards Styles */
    .box { border: 1px solid #334155; border-radius: 0.75rem; box-shadow: 0 4px 6px -1px rgb(0 0 0 / 0.1); }
    /* Logo adjustment */
    #logo { max-height: 3.5rem; }
    /* Footer cleanup */
    footer { font-size: 0.875rem; opacity: 0.6; }

# TRADUCCIONES AL ESPAÑOL
i18n:
  activeIncidents: "Incidencias Activas"
  allSystemsOperational: "✅ Todos los sistemas operativos"
  incidentReport: "Informe de incidente de "
  serviceUnderMaintenance: "🛠 Mantenimiento Programado"
  majorOutage: "🔴 Caída Mayor"
  partialOutage: "🟠 Caída Parcial"
  degradedPerformance: "🟡 Rendimiento Degradado"
  uptime: "Disponibilidad"
  pastIncidents: "Incidencias Pasadas"
  pastIncidentsResolved: "Incidencias resueltas en los últimos días"
  liveStatus: "Estado en vivo"
  overallUptime: "Disponibilidad general"
  overallUptimeTitle: "Disponibilidad general de los últimos 90 días"
  averageResponseTime: "Tiempo de respuesta medio"
